databases:
  - name: noteapp-db
    databaseName: noteapp
    user: noteapp
    plan: free

services:
  - type: web
    name: noteapp
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -p $PORT"
    envVars:
      - fromDatabase:
          name: noteapp-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
